---
title: "Choose an alpha value"
author: "Eleanor Jackson"
date: '23 January, 2023'
always_allow_html: true
output: 
  github_document:
    keep_html: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.path = "figures/2023-01-23_choose-alpha-value/")
```

```{r packages}
library("tidyverse")
```

```{r data}
readRDS(here::here("data", "clean", "pod_data.rds")) %>%
  select(tree_id, lon, lat) -> focal_jacc

plotKML::readGPX(here::here("data", "maps",
                            "jacc-map-garzonlopez2012", "jac1co_map.gpx")) %>%
  map_df( ~ .) %>%
  select(lon, lat) %>%
  mutate(tree_id = paste0("CGL_", 1:n())) -> other_jacc
```

```{r}
# remove duplicated trees
geosphere::distm(cbind(pull(focal_jacc, lon), pull(focal_jacc, lat)), 
                 cbind(pull(other_jacc, lon), pull(other_jacc, lat)), 
                 fun = distGeo) -> dist_matrix

rownames(dist_matrix) <- focal_jacc$tree_id
colnames(dist_matrix) <- other_jacc$tree_id

# assume closest tree within 30 m from focal tree is the same tree
as.data.frame.table(dist_matrix, responseName = "dist") %>% 
  filter(dist <= 30) %>%
  group_by(Var1) %>%
  slice(which.min(dist)) %>% 
  ungroup() %>%
  pull(Var2) %>%
  unique() -> duplicate_trees

rbind(other_jacc, focal_jacc) %>% 
  filter(!tree_id %in% duplicate_trees) -> all_jacc
```

```{r}
# calculate pairwise distances

calculate_dist <- function (data) {
  
  data %>%
    select(lat, lon) -> plot_matrix
  
  rdist::pdist(plot_matrix[,c("lat", "lon")], 
               metric = "euclidean") -> dists
  
  as.data.frame(dists) -> dists_df
  
  unlist(data$tree_id) -> colnames(dists_df) 
  
  cbind(data, dists_df)
  
}

distance_df <- calculate_dist(all_jacc)
```


```{r}

focal_jacc %>%
  distinct(tree_id) %>%
  pull(tree_id) -> focal_tree_id_list

tibble(alpha = c(10 , 20, 30, 40, 50, 60)) -> alpha_list

merge(focal_tree_id_list, alpha_list) %>%
  rename(id = x) -> alpha_tree_id

c

connectivity_dfs <- pmap(alpha_tree_id, .f = calculate_connectivity, data = distance_df)

connectivity_dfs %>%
  dplyr::bind_rows() -> all_connectivity_dfs

readRDS(here::here("data", "clean", "pod_data.rds")) %>%
  drop_na() %>%
  mutate_at(c("n_total", "n_predated"), round) %>%
  left_join(all_connectivity_dfs) %>%
  group_by(alpha) %>%
  group_split() -> connectivity_dfs_alpha

```

```{r}

fit_glmms <- function (data) {
  
  lme4::glmer(data, 
              formula = cbind(n_predated, (n_total - n_predated)) ~ log(connectivity) + (1| dbh_mm), 
    family = "binomial")
  
}

models <- lapply(connectivity_dfs_alpha, fit_glmms)

lapply(models, AIC)

```

